version: '3'
services:
  taibai-redis-service:
    container_name: taibai-redis-container
    image: "redis:alpine"

  taibai-support-service:
    container_name: taibai-support-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        branch_name: "master"
    environment:
      - rabbitmq_addr
      - rabbitmq_user
      - rabbitmq_passwd
      - classroom_region
    ports:
      - "8888:8888"
    depends_on:
      - taibai-redis-service

